### ISSUE TITLE
Missing clock.py file

### ISSUE THREAD

**Issue by dandspach** [cjudd/binary-clock-workshop#2]
Very cool project, and just what I've been looking for.  However, I can't find the clock.py file.  Am I missing something?

**Comment by cjudd** [comment]
Great question. It is in the raspian image provided in the setup instruction. It is also in a different github repo - https://github.com/cjudd/binary-clock. I will update the documentation to include that.

**Comment by dandspach** [comment]
Thanks.  Very cool project.  My son and I are making one or two of them.



Sent from Mail for Windows
